name: Deploy to Render

on:
  push:
    branches:
      - main

env:
  RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}

jobs:
  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: render-registry.net/${{ env.RENDER_PROJECT_NAME }}/${{ env.RENDER_SERVICE_NAME }}:${{ env.RENDER_IMAGE_TAG }}

    - name: Deploy to Render
      uses: render-examples/render-docker-deploy@v1
      with:
        api_key: ${{ env.RENDER_API_KEY }}
        project_name: ${{ env.RENDER_PROJECT_NAME }}
        service_name: ${{ env.RENDER_SERVICE_NAME }}
        image: render-registry.net/${{ env.RENDER_PROJECT_NAME }}/${{ env.RENDER_SERVICE_NAME }}:${{ env.RENDER_IMAGE_TAG }}
        wait: true
